### ISSUE TITLE
Linux系列报错

### ISSUE THREAD

**Issue by Z-fly** [ghosx/TiebaProject#10]
错误日志
![image](https://user-images.githubusercontent.com/10470892/60231587-4fbc4680-98cc-11e9-88bc-b7a12b9d6152.png)
gevent报错，定时任务无法执行
复现：CentOS、Kali等

此解决方法亲测无效
https://blog.csdn.net/chong_yun/article/details/80815704

**Comment by ghosx** [comment]
https://blog.csdn.net/baidu_24536755/article/details/80712903

**Comment by Z-fly** [comment]
> https://blog.csdn.net/baidu_24536755/article/details/80712903

试过了，还是没有用
