### ISSUE TITLE
回帖可以自定义内容吗

### ISSUE THREAD

**Issue by ctaoist** [ghosx/TiebaProject#11]
回帖能够加上自定义内容吗
比如不同的贴子，需要回不同的内容
或者是填入多段内容，每次随机选一个回，也可以回固定内容
还有云回的时间单位是什么啊，分钟？

**Comment by ghosx** [comment]
分钟
项目目前正在重构

**Comment by ctaoist** [comment]
之前一用就被关小黑屋。。。
