### ISSUE TITLE
登录后关注新吧不会签到

### ISSUE THREAD

**Issue by pplokijuhyg** [ghosx/TiebaProject#15]
当扫码登录完成后，再进行关注贴吧，第二天不会自动签到

**Comment by ghosx** [comment]
系统会在每晚21点获取新关注的贴吧并进行签到
我刚测试是没有问题的，如果还有问题请提供相关账号协助排查

**Comment by pplokijuhyg** [comment]
邮箱发你了

**Comment by pplokijuhyg** [comment]
> 系统会在每晚21点获取新关注的贴吧并进行签到
> 我刚测试是没有问题的，如果还有问题请提供相关账号协助排查

邮箱发你了
